# Generated by Django 4.0.4 on 2022-12-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat_app', '0002_sanctioning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoter',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
