# Generated by Django 4.0.4 on 2023-01-03 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('combat_app', '0007_fighter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promoter',
            old_name='profile_img',
            new_name='profile',
        ),
    ]
