# Generated by Django 4.0.4 on 2023-01-04 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('combat_app', '0009_alter_sanctioning_profile_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sanctioning',
            old_name='profile_img',
            new_name='profile',
        ),
    ]
