# Generated by Django 4.0.4 on 2023-01-04 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat_app', '0010_rename_profile_img_sanctioning_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanctioning',
            name='profile',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
    ]
