# Generated by Django 4.0.4 on 2023-01-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat_app', '0011_alter_sanctioning_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fighter',
            name='profile_img',
        ),
        migrations.RemoveField(
            model_name='gym_owner',
            name='profile_img',
        ),
        migrations.RemoveField(
            model_name='medics',
            name='profile_img',
        ),
        migrations.AddField(
            model_name='fighter',
            name='profile',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='gym_owner',
            name='profile',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='medics',
            name='profile',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
    ]
