# Generated by Django 4.0.4 on 2023-01-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat_app', '0012_remove_fighter_profile_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('profile', models.ImageField(blank=True, max_length=200, null=True, upload_to='')),
                ('email', models.EmailField(max_length=300)),
                ('contact', models.EmailField(max_length=20)),
                ('date', models.IntegerField()),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=80)),
                ('town', models.CharField(max_length=80)),
                ('country', models.CharField(max_length=80)),
                ('document', models.FileField(max_length=250, upload_to='new/')),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
