# Generated by Django 4.0.4 on 2023-01-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat_app', '0013_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanctioning',
            name='document',
            field=models.FileField(max_length=250, null=True, upload_to=''),
        ),
    ]
