# Generated by Django 4.0.4 on 2023-01-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat_app', '0014_alter_sanctioning_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('month', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('discipline', models.CharField(max_length=100)),
                ('Sanct_body', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('medics', models.CharField(max_length=50)),
                ('host', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=20)),
            ],
        ),
    ]
