# Generated by Django 4.0.4 on 2023-01-12 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('combat_app', '0015_event_calendar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_calendar',
            old_name='Sanct_body',
            new_name='sanct_body',
        ),
    ]
