# Generated by Django 4.0.4 on 2023-01-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat_app', '0018_register_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='contact',
            field=models.CharField(max_length=20),
        ),
    ]
