# Generated by Django 4.0.4 on 2023-01-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat_app', '0019_alter_fighter_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='discipline',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
